# Generated by Django 5.1.4 on 2024-12-20 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.RemoveField(
            model_name='url',
            name='store',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='URL',
        ),
    ]
