# Generated by Django 5.1.4 on 2024-12-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0002_delete_history_remove_url_store_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now=True)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('offer', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.store')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.store')),
            ],
        ),
    ]
